### ISSUE TITLE
Manual testing

### ISSUE THREAD

**Issue by kriman** [BME-MIT-IET/iet-hf-2023-nemtomge#6]

**Comment by kriman** [comment]
@boriiza please see /test/ for test samples and /docs/08_proto_teszt.pdf and /docs/Bemeneti-kimeneti_nyelv.pdf for test documentation

**Comment by boriiza** [comment]
I created a Jira board for manual testing: https://nemtomge.atlassian.net/jira/software/projects/NEM/boards/1/roadmap?shared=&atlOrigin=eyJpIjoiNWY3ZjkzZTJlYTZkNDIxNGE1MjZmOGQ0ODJhN2M5MzgiLCJwIjoiaiJ9

**Comment by kriman** [comment]
Results are here: [https://prezi.com/i/view/CW7YeCAz865sXrJRHRAh/](https://prezi.com/i/view/CW7YeCAz865sXrJRHRAh/)

**Comment by kriman** [comment]
@boriiza Could you please upload the presentation to the `/doc` folder? (NOT the `/docs`)
